version: '3.8'

services:
  devcontainer:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - devcontainer-shell-history:/home/ubuntu/.shell_history
      - claude-auth:/home/ubuntu/.config/claude
      - github-cli-auth:/home/ubuntu/.config/gh
      - ${PWD}/.claude:/home/ubuntu/.claude:cached
      - ${HOME}/.claude.json:/home/ubuntu/.claude.json:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_DEFAULT_REGION: us-east-1
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports:
      - "8083:8000"

volumes:
  devcontainer-shell-history:
  claude-auth:
  github-cli-auth: